GitHub Actions

diff --git a/.github/workflows/coolify-deploy.yml b/.github/workflows/coolify-deploy.yml
--- a/.github/workflows/coolify-deploy.yml
+++ b/.github/workflows/coolify-deploy.yml
@@ -4,6 +4,11 @@ on:
   push:
     branches: [ main ]
 
+env:
+  API_URL: ${{ secrets.COOLIFY_API_URL }}
+  SERVICE: ${{ secrets.COOLIFY_SERVICE_ID }}
+  AUTH_HEADER: 'Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}'
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -11,11 +16,20 @@ jobs:
     steps:
       - name: install jq
         run: sudo apt-get install jq
-      - name: run deploy
+      - name: start deploy
+        id: start_deploy
         run: |
-          response=$(curl --request GET '${{ secrets.COOLIFY_API_URL }}/api/v1/deploy?uuid=${{ secrets.COOLIFY_SERVICE_ID }}&force=false' --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}')
+          response=$(curl --request GET '$API_URL/api/v1/deploy?uuid=$SERVICE&force=false' --header '$AUTH_HEADER')
           deployment_uuid=$(echo $response | jq -r '.deployments[0].deployment_uuid')
-          
+          if [[ "deployment_uuid" == "null" ]]; then
+            echo "Failed to start deployment: \n$response"
+            exit 1
+          fi
+          echo "deployment_uuid=$deployment_uuid" >> $GITHUB_OUTPUT
+      - name: check status
+        with:
+          deployment_uuid: ${{ steps.vars.outputs.deployment_uuid }}
+        run: |
           status=""
           deployment_url=""
           
@@ -27,14 +41,18 @@ jobs:
           do
             sleep $period
             count=$(( $count + 1 ))
-            response=$(curl --request GET '${{ secrets.COOLIFY_API_URL }}/api/v1/deployments/$deployment_uuid' --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}')
+            response=$(curl --request GET '$API_URL/api/v1/deployments/$deployment_uuid' --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}')
             status=$(echo $response | jq -r '.status')
+            if [[ "status" == "null" ]]; then
+              echo "Deployment failed: \n$response"
+              exit 1
+            fi
             deployment_url=$(echo $response | jq -r '.deployment_url')
           done
           
           if [ "$status" != "deployed" ]; then
-            echo "Deployment failed after 5 minutes. More info at ${{ secrets.COOLIFY_API_URL }}/$deployment_url"
+            echo "Deployment failed after 5 minutes. More info at $API_URL/$deployment_url"
             exit 1
           fi
           
-          echo "Deployment finished successfully. More info at ${{ secrets.COOLIFY_API_URL }}/$deployment_url"
+          echo "Deployment finished successfully. More info at $API_URL/$deployment_url"
